### PR TITLE
Pass RPC parameters

### PR DESCRIPTION
**Pull request by pacewicz**
Method parameters are entirely missing from requests like uploading mission or getting MAVLink parameters.
A copy-paste from [Java templates](https://github.com/mavlink/MAVSDK-Java/tree/master/sdk/templates) @480bdc8 made some method parameters appear (`string`s), still no luck with `UploadMission()` where a collection of MissionItems is expected.

Once the parameters are there, the TODO parts will need to be adjusted (converted from Java).

### CODE REVIEW

**Comment by JonasVautherin** [comment]
Because [`DownloadMission`](https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/mission/mission.proto#L98) returns something (except for the error result), it is categorized as a "request", and generated from the `request.j2` template.

[`UploadMission`](https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/mission/mission.proto#L89) doesn't return anything (except for the error result), and therefore it is a "call", coming from `call.j2`. So that's the reason why it doesn't get generated in this PR: you only edited `request.j2`.

Similarly, you will probably want to add the function arguments in `stream.j2`.

I understand that this is a bit confusing, and we could probably improve that by sharing code between the templates, but well, that's how it is at the moment :innocent:.

Thanks for the help, @pacewicz, that's really appreciated! :blush:

**Comment by pacewicz** [comment]
Thank you for clarifying how it works @JonasVautherin!  I'm just really new to templates here.

> [`UploadMission`](https://github.com/mavlink/MAVSDK-Proto/blob/master/protos/mission/mission.proto#L89) doesn't return anything (except for the error result), and therefore it is a "call", coming from `call.j2`

Modifying `call.j2` did yield the expected result - I can upload and start missions! I will refactor the code and make it another PR.

> Similarly, you will probably want to add the function arguments in `stream.j2`.

I did that - but the code did not change. Wondering if that could change when we update protos to the latest version. Anyway, not including the code for now.

**Comment by JonasVautherin** [comment]
Hmm actually, maybe we don't have any stream that takes arguments, which is why it doesn't change anything. Not sure =).

What do you mean with another PR? Couldn't we go on with this one?

Thanks a lot by the way, that's super cool!

**Comment by pacewicz** [comment]
> What do you mean with another PR? Couldn't we go on with this one?

Well, this PR was initially supposed to be about just passing RPC parameters - that feature could have gone in while I worked further. I mean to me the mission upload example would naturally be another PR because the changes are logically separate (even though it is the mission upload case that triggered them). On the other hand, I agree it does not really matter with a codebase still this small 😅

> Thanks a lot by the way, that's super cool!

I feel the same coming back to the project after a while and seeing it work (with your ongoing support, thank you)!

**Review by JonasVautherin — APPROVED** [review]

**Comment by JonasVautherin** [comment]
Got it! Well I don't have a strong opinion on this, just do what's more convenient for you. As you say it's still a small codebase, and that PR is still easy for me to review.

I think we can merge that! That's super cool!

**Pull request merged**
